---
- name: Basic playbook to check if ssh even works
  hosts: my_vm
  tasks:
    - name: Check the system information
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}. Full: {{ ansible_lsb['description'] }}. Home is {{ ansible_env['HOME'] }}"
    - name: List all known hosts
      debug:
        var: groups['all']
    - name: Execute some command on shell
      ansible.builtin.shell:
        cat ~/.ssh/authorized_keys
      register: home_dir

    - name:  Stdout from previous command
      debug:
        msg: "{{ home_dir.stdout }}"
    
    - name: Fetch hello-world container data
      community.docker.docker_container_info:
        name: hello-worldasdads
      register: result

    - name: Check if the container exists
      debug:
        msg: "Does the container exist? {{ 'yes' if result.exists else 'no' }}"