---
amf:
  ngap_ip: "{{ ip_c_plane }}"

smf:
  pfcp_ip: "{{ ip_c_plane }}"
  gtpu_ip: "{{ ip_c_plane }}"
  
  upf_confs:
    - addr: "{{ ip_u_plane1 }}"
      dnn: ['internet', 'internet2']
    - addr: "{{ ip_u_plane2 }}"
      dnn: ['ims']

configs:
  - 'amf'
  - 'smf'