---
amf:
  ngap_ip: "{{ ip_c_plane }}"

smf:
  pfcp_ip: "{{ ip_c_plane }}"
  gtpu_ip: "{{ ip_c_plane }}"
  
  upf_confs:
    - addr: "{{ ip_u_plane1 }}"
      dnn_slice_end: 2  # Take 0th and 1st dnn
    - addr: "{{ ip_u_plane2 }}"
      dnn_slice_start: 2  # Take 2nd dnn

configs:
  - 'amf'
  - 'smf'