---

# gnb
mcc: 999
mnc: 99
gnb:
  ip: "{{ ansible_host }}"
  AmfConfigs_ip: "{{ hostvars['open5gs1'].ansible_host }}"
ue:
  supi: 'imsi-999990000000001'

clone_dest: "/home/{{ ansible_env.SUDO_USER }}/UERANSIM"
configs:
  - 'gnb'
  - 'ue'
