---
clone_dest: "/home/{{ ansible_env.SUDO_USER }}/UERANSIM"
# gnb
gnb:
  mcc: 999
  mnc: 99
  ngapIp: "{{ ansible_host }}"
  gtpIp: "{{ ansible_host }}"
  AmfConfigs:
    address: "{{ hostvars['open5gs1'].ansible_host }}"

ue:
  supi: 'imsi-999990000000001'
  mcc: 999
  mnc: 99
