---
# tasks file for install_open5gs role
- name: Install Open5gs for the machines designed for Open5gs
  include_tasks: open5gs.yml
  when: install

- name: Launch templating playbook for testing
  include_tasks: template_testing.yml