---
- name: Template specified config files for Open5gs
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/{{ item }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop: "{{ configs }}"

- name: Template the startup script
  ansible.builtin.template:
    src: "scripts/{% if 'C' in inventory_hostname %}start_C_plane{% else %}start_U_plane{% endif %}.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/start_sim.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'

- name: Template script for enabling connectivity
  ansible.builtin.template:
    src: "scripts/configure_connectivity.sh.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/configure_connectivity.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'U' in inventory_hostname"

- name: Template script for packet capture
  ansible.builtin.template:
    src: "scripts/capture.sh.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/capture.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'U' in inventory_hostname"

- name: Template script for adding subscribers to db
  ansible.builtin.template:
    src: "scripts/add_subscribers.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/add_subscribers.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'C' in inventory_hostname"