---
- name: Template specified config files for Open5gs
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/{{ item }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop: "{{ configs }}"

- name: Template the startup script
  ansible.builtin.template:
    src: "scripts/{% if 'C' in inventory_hostname %}start_C_plane{% else %}start_U_plane{% endif %}.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/start_sim.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0555'