---
- name: Template specified config files for Open5gs
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/{{ item }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop: "{{ configs }}"
  when: "'open5gs' in group_names"

- name: Template the startup script
  ansible.builtin.template:
    src: "scripts/start_controlled_bg.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/start_sim.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0555'
  # vars:
    # some_var_name: override_value