---
- name: Template gnb config files for UERANSIM
  ansible.builtin.template:
    src: "open5gs-gnb.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/gnb.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  when: inventory_hostname != 'ue'

- name: Template UE configs for UERANSIM
  ansible.builtin.template:
    src: "open5gs-ue.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/ue{{ index }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop_control: 
    index_var: index
  vars:
    ue: "{{ item }}"
  loop: "{{ ues }}"
  when: inventory_hostname == 'ue'
