---
- name: Template specified config files for UERANSIM
  ansible.builtin.template:
    src: "ueransim/open5gs-{{ item }}.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/{{ item }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop: "{{ configs }}"