---
- name: Template gnb config files for UERANSIM
  ansible.builtin.template:
    src: "open5gs-gnb.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/gnb.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  when: "gnb is defined"

- name: Template UE configs for UERANSIM
  ansible.builtin.template:
    src: "open5gs-ue.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/template_test/ue{{ index }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop_control: 
    index_var: index  # To number the files
  vars:
    ue: "{{ item }}"  # The j2 template references to ue, not item, hence this needs to be specified
  loop: "{{ ues }}"
  when: "ues is defined"

- name: Template the startup script
  ansible.builtin.template:
    src: "scripts/{% if 'gnb' in inventory_hostname %}start_gnb{% else %}start_ues{% endif %}.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/start_sim.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
