---
# tasks file for install_open5gs role
- name: Ensure Open5GS is installed
  include_tasks: open5gs.yml
  when: install

- name: Template neccessary scripts and configs
  include_tasks: template.yml