---
# Tasks for installing mongodb
- name: Ensure apt signing key for Mongodb is present
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc 
    state: present
  
- name: Ensure mongodb repository is added
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse"
    state: present
  
- name: Update cache and ensure mongodb and mongosh is installed
  ansible.builtin.apt:
    pkg: 
      - mongodb-org
      - mongodb-mongosh
    state: present
    update_cache: yes

- name: Ensure MongoDB service is running
  ansible.builtin.systemd:
    name: mongod.service
    state: started
  register: mongod_info
# - name: Debug print the state of the daemon
#   debug:
#     msg: "{{ mongod_info.status['ActiveState'] }}"
- name: Wait 3s for mongodb daemon to start
  ansible.builtin.pause:
    seconds: 3
  
- name: Register MongoDB daemon status
  ansible.builtin.systemd:
    name: mongod
  register: mongod_info

- name: End the playbook execution if mongodb does not work
  fail:
    msg: "MognoDB daemon is not working!"
  when: mongod_info.status['ActiveState'] != 'active'

- name: Ensure MognoDB daemon auto-starts
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    masked: false