---
- name: Create directory for open5gs backup if not present
  ansible.builtin.file:
    dest: "/etc/open5gs_backup"
    state: directory
- name: Backup default Open5GS config files
  ansible.builtin.copy:
    remote_src: true
    src: "/etc/open5gs/"
    dest: "/etc/open5gs_backup"
- name: Template new default configs without IPv6
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/etc/open5gs/{{ item }}.yaml"
    owner: "root"
    mode: '0666'
  loop: "{{ all_configs }}"

- name: Create directories for content if not present
  ansible.builtin.file:
    path: "/home/{{ ansible_env.SUDO_USER }}/{{ item }}"
    state: directory
  loop:
    - "configs"
    - "scripts"
    - "captures"
  
- name: Template specified config files for Open5gs
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/configs/{{ item }}.yaml"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0666'
  loop: "{{ configs }}"

- name: Template the startup script for C-plane
  ansible.builtin.template:
    src: "scripts/start_C_plane.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/scripts/start_cplane.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'amf' in configs or 'smf' in configs"

- name: Template the startup script for U-plane
  ansible.builtin.template:
    src: "scripts/start_U_plane.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/scripts/start_uplane.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'upf' in configs"

- name: Template script for enabling connectivity
  ansible.builtin.template:
    src: "scripts/configure_connectivity.sh.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/scripts/configure_connectivity.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'upf' in configs"

- name: Template script for packet capture
  ansible.builtin.template:
    src: "scripts/capture.sh.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/scripts/capture.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  # when: "'U' in inventory_hostname"

- name: Template script for adding subscribers to db
  ansible.builtin.template:
    src: "scripts/add_subscribers.sh"
    dest: "/home/{{ ansible_env.SUDO_USER }}/scripts/add_subscribers.sh"
    owner: "{{ ansible_env.SUDO_USER }}"
    mode: '0777'
  when: "'amf' in configs or 'smf' in configs"

- name: Template the instruction text file
  ansible.builtin.template:
    src: "instruction.txt.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/instruction.txt"
    mode: '0444'
  