---
- name: Ensure required dependencies are present
  block:
    - name: Ensure neccessary apt packages are present
      ansible.builtin.apt:
        pkg:
        - dialog
        - apt-utils
        - build-essential
        - libsctp-dev
        - lksctp-tools
        - iproute2
        - g++
        - screen
        update_cache: yes
        state: present

    - name: Ensure cmake from snap is installed
      community.general.snap:
        name: cmake
        classic: true

- name: Ensure UERANSIM repository is present on system
  become: false  # To avoid file ownership issues
  ansible.builtin.git:
    repo: "https://github.com/aligungr/UERANSIM"
    dest: "/home/{{ ansible_env.SUDO_USER }}/UERANSIM"
    clone: yes

- name: Compile the UERANSIM src code with Make
  become: false
  community.general.make:
    chdir: "/home/{{ ansible_env.SUDO_USER }}/UERANSIM"

- name: Ensure the machine hostname is equal to inventory_hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_task

- name: Restart the machine if needed
  ansible.builtin.reboot:
    pre_reboot_delay: 5 # Included due to a hang on restart
    reboot_timeout: 180 # 3 minute timeout for restart. Manual intervention required if this task fails
  when: hostname_task is changed